let periods = {
    period1: {
        sections: [
            {
                title: 'Discovery',
                body:
                    'In 1492, Genoan sailor Christopher Columbus had discovered the island of Hispaniola while sailing under the Spanish flag. He initially assumed that he had made it to India, as he intended, but really discovered an island in the Americas. Here, Columbus met the true residents of the Americas, who had never seen anyone like Columbus and the Spanish before. He also found new crops, like corn. Eventually, Columbus had made multiple voyages to the New World, and had even enslaved the native population for his own gain. Following Columbus’ journey, the French and Spanish started to come to the New World for business. The Spanish had set up the encomienda system to use the native population for labor in exchange for food and shelter. They also hoped to convert the natives to Catholicism. The French on the other hand were purely interested in business, and had traded items such as animal skins with the natives.',
                image: '/images/p1images/Columbus.jpg'
            },
            {
                title: 'Jamestown',
                body:
                    'The Virginia Company, also known as the Virginia Company of London, was a commercial trading company which was overlooked by King James I of England in April 1606. The main objective of the company is to colonize the eastern coast of North America. The company was also in charge of the Jamestown enterprise. During the first two years of its existence, the Virginia colony was a bad investment, mainly because of the unwillingness of the early settlers to do the necessary work to combat the shortage of capital to supply the venture. Because of this, Jamestown was suffering. In 1609, the departure of colony leader John Smith had turned things for the worse, where the people of the colony did not have enough food and suffered dearly, creating the Starving Winter. But, Jamestown did start to improve, thanks to the efforts of farmer John Rolfe, who discovered a way to use tobacco, making Jamestown a profitable venture. In 1619, two major things occurred. First, the House of Burgesses was established, the first local government in the colonies. Secondly, a Portuguese slave ship brought the first Africans to the New World, as indentured servants. For the next couple decades Jamestown survived, occasionally fighting with local native tribes. Come 1676, the colonies’ first revolt occurred, Bacon’s Rebellion. Bacon’s Rebellion was a movement headed by Nathaniel Bacon against the corrupt governor of Jamestown William Berkeley. He killed Berkeley and burned Jamestown to the ground with a group of allies made of disgruntled colonists and indentured servants. Following this, Jamestown was abandoned.',
                image: '/images/p1images/Jamestown.jpg'
            },
            {
                title: 'The New England Colonies',
                body:
                    `Although lacking a charter, the founders of Plymouth in Massachusetts were dependent on the private investments to assist in financing the colony. The major point of that settlement involved Leiden, Holland (now in the Netherlands). The enclave of English emigres was Separatists, the English protestants in the 16th and 17th centuries who wished to separate themselves from the perceived corruption of the Church of England, believed that the true church was a voluntary company of the faithful under the guidance of a pastor and tended to be exceedingly individualistic in church matters. 

                    In 1620, nearly half of the Pilgrims died, within the first year of settlement, due to disease. However, as time progressed with little support from the English investors, the overall health and economic position of the colonists improved. Pilgrims further developed peace treaties with Indians around them, which enabled them to devote their time to building a strong, stable economic base. Although none of their principal economic activities, such as farming and fishing, promised them lavish wealth, the Pilgrims were only able to be self-sufficient for five years. The Pilgrims were a minority in Plymouth and yet had solidified their control on the entire governmental structure of their colony during the first four decades of their settlement. Before embarking on a voyage in the Mayflower, William Bradford required that all the adult males aboard who were able to do so sign compact promising obedience to the laws and ordinances drafted by the leaders of the enterprise. The Mayflower Compact has been interpreted as an important step in the evolution of democratic government in America.
                    
                    Another colony was Massachusetts Bay. The Puritans of Massachusetts Bay Colony, like the pilgrims, sailed to America to essentially free themselves from the religious restraints. However, what made the Puritans different from the Pilgrims was that they did not want to separate themselves from the Church of England but, rather, hoped by their example to reform it. The civil government of the colony was guided by similar authoritarian principles. Men such as John Winthrop, the first governor of Massachusetts Bay, believed that it was the duty of the governors of society not to act as the direct representatives for their constituents but rather to decide, independently, what measures were in the best interest of the total society. Despite the authoritarian tendencies of the Massachusetts Bay Colony, a spirit of community developed there as perhaps in no other colony. Although life in Massachusetts was made difficult for those who dissented from the prevailing orthodoxy, it was marked by a feeling of attachment and community for those who lived within the enforced consensus of the society. Roger Williams, the man closely associated with the founding of Rhode Island, was banished from Massachusetts because of his unwillingness to conform to the orthodoxy established by that colony. Williams showed distinctly Separatist leanings, preaching that the Puritans church could not possibly achieve purity as long as it remained within the Church of England. Due to the religious basis of the Massachusetts Bay colony, all supernatural dealings were scrutinized. The Salem witch trials were a series of hearings and prosecutions of people accused of witchcraft in colonial Massachusetts between February 1692 and May 1693. More than 200 people were accused. Thirty were found guilty, nineteen of whom were executed by hanging. In reality, more likely than not, no one was involved in the Dark Arts.
                    
                    New Netherland, founded in 1624 at Fort Orange (now Albany) by the Dutch West India Company, was but one element in a wider program of Dutch expansion in the first half of the 17th century. In 1664 the English captured the colony of New Netherland, renaming it New York after James, Duke of York, brother of Charles II, and placing it under the proprietary control of the duke. It was the first major city of the colonies in the New World.`,
                image: '/images/p1images/MBC.jpg'
            },
            {
                title: 'Imperial Organization',
                body:
                    'British policy toward the American colonies was inevitably affected by the domestic politics of England; since the politics of England in the 17th and 18th centuries. It was nearly impossible for England to predict what role Virginia, Maryland, Massachusetts, Connecticut, but Rhode Island would play in the overall scheme of empire because of the diversity of the aims and governmental structures of those colonies. The Navigation Act of 1660, a modification and amplification of a temporary series of acts passed in 1651, provided that goods bound to England or to English colonies, regardless of origin, had to be shipped only in English vessels; that three-fourths of the personnel of those ships had to be Englishmen; and that certain “enumerated articles,” such as sugar, cotton, and tobacco, were to be shipped only to England, with trade-in those items with other countries prohibited.The distance separating England and America, the powerful pressures exerted on royal officials by Americans, and the inevitable inefficiency of any large bureaucracy all served to weaken royal power and to strengthen the hold of provincial leaders on the affairs of their respective colonies. By the mid-18th century, most political power in America was concentrated in the hands of provincial rather than royal officials. These provincial leaders undoubtedly represented the interests of their constituents more faithfully than any royal official could, but it is clear that the politics of provincial America were hardly democratic by modern standards. Provincial America became less dependent on subsistence agriculture and more on the cultivation and manufacture of products for the world market. Land, which initially served only individual needs, came to be the fundamental source of economic growth. New England turned its land over to the raising of meat products for export. The middle colonies were the principal producers of grains. The Southern colonies were, of course, even more closely tied to the cash crop system.',
                image: ''
            },
            {
                title: 'French and Indian War',
                body:
                    'The French and Indian War (1754-1763), also known as the “seven-year war,” pitted the colonies of British America against those of New France, each side supported by military units from the parent country and by American Indian allies. In July 1758, the British won their first great victory at Louisbourg, near the mouth of the St. Lawrence River. A month later, they took Fort Frontenac at the western end of the river. In November 1758, General John Forbes captured Fort Duquesne for the British after the French destroyed and abandoned it, and Fort Pitt was built on the site, giving the British a key stronghold. This led to the eventual British victory. The French and Indian War ended with the signing of the Treaty of Paris in February 1763. The British received Canada from France and Florida from Spain but permitted France to keep its West Indian sugar islands and gave Louisiana to Spain. The arrangement strengthened the American colonies significantly by removing their European rivals to the north and south and opening the Mississippi Valley to westward expansion.',
                image: '/images/p1images/FIW.jpg'
            },
            {
                title: 'Writing Tips',
                body:
                    'Typically, the focus of essays compares the colonies, so what was the difference between Jamestown and Massachusetts Bay? For prompts like these, it is best to address the political, economic, and social aspects of the colonies and compare and contrast them.',
                image: ''
            }
        ]
    },
    period2: {
        sections: [
            {
                title: 'The Road to Revolution',
                body:
                    `Following the 7 Years War, the British had faced monetary issues, due to the maintenance of their colonies and the costs of war. To remedy the issue, the British had increased taxes, and since they had an impression they had been very loose with how they treated the American colonies, they imposed large taxes on the colonies, which we’ll detail below. As it will be seen, this action by the British, coupled with the Royal Proclamation of 1763 which prevented American colonists from going beyond the line, limiting colonial expansion, would lead to Revolution. 

                    The first act passed by British Prime Minister George Grenville was known as the Sugar Act of 1764. The Sugar Act had placed a tax on imported refined sugar and molasses from non-British Carribean sources in order to raise money for the crown. This act was followed by the Currency Act of 1764, which took paper money out of circulation from the colonies, mainly due to the fact it was depreciated in value in the eyes of the British. This allowed the British to really assume control of the existing colonial money. In 1765, the British passed the Stamp Act, which taxed the colonists on English-stamped printed materials. This act of direct taxation, combined with the two aforementioned taxes, had outraged the colonists and led to rioting, the tarring and feathering of stamp agents, and the destruction of the stamped goods by colonists like the Sons of Liberty, a group formed by John and Samuel Adams to oppose the Stamp Act. Alongside these activities, the “Stamp Act Congress”, consisting of members from 9 of the colonies came together to create a statement of grievances to be sent to King George III. In 1766, after dealing with so much outrage and seeing an impact on English business, Parliament repealed the Stamp Act, and issued a new act called the Declaratory Act which stated that Britain was allowed to directly tax any of its colonies. The unity that occurred to fight the Stamp Act would foreshadow and set the stage for the Independence movement a decade later. 
                    
                    In 1767, the new Prime Minister of Great Britain, Charles Townshend, decided to control the colonies through the passage of 4 laws, known as the Townshend Acts. The main act that disturbed the colonists was the taxes on a variety of goods that were imported into the colonies, since it made their way of life more difficult. Other tenets, such as beefing up the Quartering Act of 1765, and more restricted control over customs of the colonies, took away from the policy of “salutary neglect”, the hands-off approach of the Crown,  the colonists had felt prior to 1763. The Townshend Acts had caused small hostilities between the British and colonists, which culminated on March 5, 1770 with the infamous Boston Massacre. In this incident, protestors of the British measures were throwing snowballs and other materials at British soldiers, leading to Capt. Thomas Preston ordering his soldiers to fire on the crowd, killing 3 men, including sailor and former slave Crispus Attucks. Coincidentally, namely due to violence like this against British merchants and servants, Parliament had repealed the Townshend Acts on the same day. Soldiers were also removed from Boston to avoid conflict. The Boston Massacre would go on to be an event that would be remembered and a reason to fight for independence. 
                    
                    Following this, tensions were relatively calm until 1773. In 1773, due to an overabundance of tea in British East India Company, which was a mercantile corporation, the British decided to sell the tea to the colonies at a discount. Colonists had interpreted the Tea Act to be a nefarious move by the British. Due to discounted tea being sold by the East India Company directly to the colonies, colonial tea merchants were losing sales, and other colonists believed that the Tea Act was really a means to trick the colonists into paying for imported tea so they would pay the already existing tax on it. These anti-Tea Act colonists decided to act to show their dissatisfaction. On December 16, 1773, the colonists dressed up as Native Americans and poured tea out of ships into Boston Harbor as protest against the Tea Act. While the Boston Tea Party was not approved by all future independence movement leaders, it did awaken some feelings of rebellion which influenced the inception of the independence movement. The Boston Tea Party’s more immediate result was the levying of the Coercive Acts, otherwise known as the Intolerable Acts. The Intolerable Acts were mainly focused on Massachusetts as retribution for the Boston Tea Party. Boston’s port was closed until all the spilled tea was paid for, Massachusetts households were mandated to quarter troops, judicial authority was moved to England, and the Massachusetts Constitution was ended. All in all, the measures of the acts resembled martial law in Massachusetts. While these acts were placed against the colonies in a bid to squash the rebellion, it had the opposite effect, energizing the colonies to fight against Great Britain. 
                    
                    This led to the creation of the first Continental Congress. Here, representatives of 12 of the 13 colonies came together to air their grievances against the Crown, eventually drafting papers like the Olive Branch Petition to do so, requesting representation in Parliament, to which the British stated they were already virtually represented. The Association was also passed here to unite in boycotting British goods. 
                    
                    On April 19, 1775, conflict had finally erupted. The night before, the colonists learned that the British aimed to seize an arms cache in Concord, which led to Paul Revere doing his night ride alerting the revolutionaries. The colonists positioned themselves for the battle, and fought against the British. With “the shot heard around the world”, the Revolutionary War had begun.`,
                image: '/images/p2images/BM.jpg'
            },
            {
                title: 'The Revolutionary war',
                body: 
                    `Following the Battle of Lexington and Concord, the next noteworthy battle happened in June 1775 on Breed’s Hill, the Battle of Bunker Hill. Although the colonists were defeated at the battle, they had dealt significant casualties upon the English, which renewed their morale and allowed them to continue fighting the English. Although the colonists were outnumbered and more disorganized, they had advantages against the English in provisions, training, interest and morale, and geography during the war. While smaller conflicts continued to occur, the colonies had not formally filed for independence. At the Second Continental Congress in 1775, George Washington was made Commander-in-Chief of the Continental Army, setting up a structure for the colonial fighting force. One of the texts that pushed for independence was 1776’s Common Sense by Thomas Paine, which argued for independence. Eventually, on July 4th, 1776, the leaders of the movement met and officially drafted and signed the Declaration of Independence, a statement freeing the colonies from Britain politically while continuing the war effort. 

                    The war continued on with many noteworthy battles, such as the Battle of Trenton, where Commander-in-Chief Washington crossed the Delaware River at night to attack enemy soldiers on Christmas Day, or the Battle of Saratoga, a Revolutionary victory which convinced the French to join in the war against the English for American Independence. The war’s final battle was at Yorktown in 1781, where General Cornwallis of the British Army surrendered after days of fighting. The official recognition of American Independence was made through the Treaty of Paris negotiated by colonists John Jay, Benjamin Franklin, and John Adams, ceding land as far as the Mississippi River. Thus, after a grueling war, American Independence was finally achieved.`,
                image: '/images/p2images/L&C.jpg'
            },
            {
                title: 'A New Government',
                body: `In 1781, after the war ended, all the colonies had ratified a new governing document and system, the Articles of Confederation. This form of government had a federal and state level system, with a goal to make sure the federal component was not too powerful, since doing so could lead to tyranny. Unfortunately, this goal would be the undoing of the Articles, since the federal government was too weak to exercise its power to fulfill its responsibility of paying off war debts. This weakness, such as no standing army or proper union, would lead to events like Shays’ Rebellion, which was an attempt by former Continental Army member Daniel Shays to obtain money for his service, and the Rebellion took a while to put down due to a lack of army. Other clauses, such as permitting states to go to war with another, needing unanimous votes to pass new laws at the federal level, and only a congressional branch of the federal government. With new territories being added to the US, as those through the Northwest Land Ordinance, a cry for a new governing document was heard. For this reason, the leaders of the new country met in Philadelphia at the Constitutional Convention to create the Constitution of the United States. 

                The Constitution had focused on creating a stronger and equally balanced federal government along with states’ rights. The deciding factor was dependent on the Virginia Plan from those who were classified as Federalists and the New Jersey plan by the Anti-federalists. This called for creating the three branches of government with separation of powers, the Executive, Legislative, and Judicial branches. The Executive branch had the President, who was decided to be George Washington, who would authorize laws and lead the country by a democratic policy. The check would be by the Legislative Branch, which would pass laws through 2 chambers, one with representatives from each state being represented by population size, which was determined as ⅗ for slaves in the nation, while the other had equal representation for each state. The Judicial Branch would be home to the Supreme Court, which checked for the legality of laws. To protect the individuals of the nation, and the states, from tyranny, the Constitution also included a bill of rights, modeled after the English one drafted on the writing of John Locke in 1688. The Constitution had set up a new effective government for centuries to come, but also opened up the existence of political parties in the Federalists, who supported more power to the federal government, and the Anti-Federalists, who believed in more power to the states.`,
                image: '/images/p2images/CC.jpg'
            },
            {
                title: 'Writing tips',
                body:
                'Typically, LAQs will be focused on the differences between the Articles of Confederation and the Constitution, with a main focus on how they affected how their country was run or why one was worse than the other. Another possible focus is on how the tax laws angered the colonists.',
                image: ''
            }
        ]
    },
    period3: {
        sections: [
            {
                title: 'The Washington Presidency',
                body:
                    `Following his appointment as President of the United States at the Constitutional Convention, Washington’s presidency was mainly a time in which the beliefs and structure of the government were more solidified. To begin, Washington had appointed members of his cabinet, like John Adams as Vice President and Alexander Hamilton as Secretary of the Treasury. His presidency had also begun with the passing of the controversial Tariff Act of 1789, which was controversial since part of the reason the colonies broke away from Britain was to avoid paying tariffs. This act had placed taxes on foreign goods, mainly English, in order to allow the United States’ industries to grow and to also produce revenue for the federal government, since no other method seemed viable. Next, Washington had moved to deal with economic structure for the new nation. The plans he considered the most were from Alexander Hamilton, which emphasized more power on a strong central government over the states, with ideas like assuming state debts, a national bank, the establishment of the US Mint and the US dollar, and the proposal of an excise tax on liquor. With Hamilton’s proposals, old disagreements returned, with many of the Federalists supporting Hamilton’s views and Anti-Federalists like Thomas Jefferson being opposed to such a move that would strengthen the central government. But Washington had accepted Hamilton’s plans, even though the Anti-Federalists were less enthusiastic about it, believing it to be what the states needed. In 1793, Washington had passed the Whiskey Act, which enforced Hamilton’s excise tax idea. For Americans, namely those on the frontier, the tax was an abomination and had sowed serious anger. This anger culminated into the formation of riots that seemed like rebellion. With the existence of militias and the power given by the Constitution, Washington was able to squash the rebellion. This was significant, since the Whiskey Revolt was similar to Shays’ Rebellion earlier, except in this case, it was actually possible to deal with the revolt and showed that the Constitution had invested proper power into the central government. 

                    The Washington Presidency did not just address domestic concerns though. Internationally, Washington dealt with the European countries. In 1793, Washington had declared neutrality in the ongoing French Revolutionary Wars. He also made treaties with other countries. With Spain, he commissioned Thomas Pickney to negotiate the Treaty of San Lorenzo with Spain, which allowed the US to navigate the Mississippi River. Washington also commissioned John Jay, an author of the Federalist papers, to negotiate Jay’s Treaty with Great Britain, which led to the removal of British forts in the west. Besides dealing with the European powers, Washington also had the issue of Barbary Pirates, which he used to the creation of a navy through the Naval Act of 1794 to deal with. In 1796, Washington decided not to run for another term in office, leading to an election for a new President and Vice President, who were decided to be John Adams and Thomas Jefferson respectively, two people from different political factions. In his Farewell Speech, Washington had only requested two things of the country, to not get involved in foreign conflicts, as he did not in the Neutrality Proclamation of 1793, and to avoid political parties, which he started to see emerge in the form of the Federalists and Anti-Federalists. Unfortunately, neither of these desires would be fulfilled in American History.`,
                image: '/images/p3images/WR.jpg'
            },
            {
                title: 'The Adam Presidency',
                body: `After winning the Election of 1796, John Adams, assumed the office of President on March 4, 1796. Once Adams assumed office, he faced a dilemma: what to do about the French. In keeping with Washington’s beliefs, he decided the country should maintain neutrality in the conflict between the French and the British, although the Anti-Federalists, now known as the Democratic Republicans, and the people of the US wanted to support France due to the fact they were fighting Britain and helped them win the Revolutionary War. After giving a speech in the Senate about being prepared for a French attack while being neutral and not creating hostilities, Adams assembled a team of American diplomats, John Marshall, Charles Pickney, and Elbridge Gerry, to negotiate with the French to reduce hostilities. Upon arriving in France, the diplomats only received a short meeting with Prime Minister Talleyrand, who didn’t really care to meet, and were then told by 3 of Talleyrand’s agents, referred to as agents X,Y, and Z, that if they wanted to continue negotiations, they must pay large bribes to Talleyrand and the French Republic. Due to this, the American diplomats returned home. Once word had gotten out about this exchange, Americans were furious, with calls for war against the French in place. 

                In response to the existence of possible French spies, the Federalists introduced, and Congress passed, the Alien and Sedition Acts. The Alien Acts had given the President the power to deport foreign nationals, namely the French, and increased overall citizenship requirements. The Sedition Act had penalized people who spoke ill of the administration or government. Though the acts did not have much impact on immigrants, it did hurt Republicans more due to the Sedition Acts. The discontent with the Sedition Act had led to Jefferson and James Madison drafting the Kentucky and Virginia Resolutions, which decried the Act and stated states have the right to nullify acts they find unconstitutional. With these acts in place, and the XYZ Affair, conflict between the US and France seemed inevitable. These conflicts only started after a French vessel captured a merchant vessel off of New York Harbor. Since it was obvious the US was not ready for a true war, Adams declared an unofficial war with the French, a Quasi-War. This involved not truly getting into major battles, and attempting to find diplomatic solutions to their problems. During this time, Adams, while attempting to resolve the issues diplomatically, commissioned ships to attack the French ships. Adams was also looking to establish a provisional army. In deciding on who to lead this army, cracks in the Federalist Party started to show. While many Federalists wanted Alexander Hamilton to be appointed, Adams did not trust him. Instead, Adams requested George Washington to lead, who stated he wanted to have Hamilton as a second-in-command, who would be the de facto leader of the army. Adams eventually relented, after holding out and nearly causing major issues in the party. As the Election of 1800 dawned, the Federalists put forward John Adams for reelection and Charles Pickney, while the Republicans put forward Jefferson and Aaron Burr once again. Due to mass opposition from the Republicans and divisions within the Federalist Party, Adams and Pickney both came in after Jefferson and Burr. The Election of 1800 had marked a turning point in US history. It marked the presidency of the first one-term President, and also showed the American system could support a successful change in power between parties.`,
                image: '/images/p3images/XYZ.jpg'
            },
            {
                title: 'The Jefferson Presidency',
                body: `After being sworn in as President on March 4, 1801, with Aaron Burr as Vice President, one of the first things Jefferson attempted to do was reverse an Adams-era act, the Judiciary Act of 1801, where Adams appointed many Federalist leaning judges in the last days of his presidency, with the Judiciary Act of 1802. This outraged the Federalists, and led to the existence of a high profile Supreme Court by plaintiff William Marbury against Secretary of State James Madison for not providing him with his commission. This case, Marbury v. Madison (1803), would be crucial for the future of the judicial branch, for it did have Madison in the wrong for not providing commission, but also did not give Marbury his post. Chief Justice John Marshall pointed out the issue with the Judiciary Act of 1789 which created the Supreme Court, and was thus able to establish Judicial Review, the ability for the Supreme Court to declare a law unconstitutional. With a change in party came changes in politics and economics. The Democratic Republicans were more about being representative of the common man than the Federalists, so suffrage was expanded to all white men rather than just the elite. On the economic side, Jefferson believed that the national debt needed to be reduced, so he set to work reducing the debt during his administration. In his presidency, Jefferson reduced the national debt by a third by reducing budgets, military spending, and abolishing the excise tax put forth by Washington. In regards to other ventures, Jefferson had abolished the importing of slaves into the US by 1808, although he let slavery in the Untied States continue. Besides these domestic changes, Jefferson had to deal with a few foreign issues as well. In 1803, Jefferson had participated in the Louisiana Purchase, where he bought the Louisiana territory from Napoleon Bonaparte, the leader of France, for $15 million. This new territory required exploration, so Jefferson commissioned the Lewis and Clark Expedition to lay claim to the Oregon territory. Throughout his presidency, Jefferson faced an issue that plagued Washington and Adams: the impressment of US sailors by the British. This came to head in 1807, when the HMS Leopard had attacked the USS Chesapeake in the Chesapeake-Leopard Affair. The British had either killed or impressed the members of the American crew. 

                Combined with Napoleon’s policy of destroying any ships trading with the British, the US Navy was under attack from both France and Britain. This led to Jefferson enforcing the Embargo Act of 1807, which prevented trade with Britain and France, as an alternative to war. Although the act had good intentions, it was circumvented through heavy smuggling. This Chesapeake-Leopard Affair would be one of the causes of the war of 1812 down the road. Although Jefferson had the opportunity to run for re-election in 1808, he decided to follow the precedent Washington set of serving only 2 terms, which led to his Secretary of State, James Madison, becoming the new President.`,
                image: '/images/p3images/CLA.jpg'
            },
            {
                title: 'The Madison Presidency and the War of 1812',
                body: `Following his inauguration, Madison had one main issue to tackle: what to do about the British. The embargoes set forth by Jefferson weren’t working the way the government hoped, and the British were still impressing US sailors. Furthermore, Madison had to also deal with the raids committed by Native Americans on colonial cities, namely Tecumseh and his brother Tenskwatawa, the leader of a pan-tribal civilization called Prophetstown that aimed to be an independent nation of the colonies. In 1811, Tenskwatawa was killed and Prophetstown was burned down in the Battle of Tippecanoe. 

                During this time, the US was calling for war, and Madison was believing it to be the only option. Furthermore, war hawk senators like John Calhoun and Henry Clay were voted into Congress, further motivating the country to fight a war with Britain which was at the moment occupied with the Napoleonic Wars. In 1812, Madison decided to declare war against Britain, in an attempt to take Canada and convince Britain to listen to the US demands, but the initial invasion, and subsequent ones, failed. In response to this, the British decided to ally with Tecumseh and his people against the United States. Tecumseh eventually died at the Battle of the Thames in 1814, bringing an end to his vision. In 1814, the British were able to breach the country, and burned the capital to the ground, massively damaging American morale. But, this didn't end the American effort. At the Battle of Baltimore a few months later, the Americans held off a naval attack by the British at Fort Henry. This was also the battle where Francis Scott Key was inspired to write the Star-Spangled Banner, as a testament to American resolve. 
                
                Along with the victory at the Battle of Plattsburgh, and anti-war sentiments of the British public, the war started to turn in the Americans’ favor, ending with the Battle of New Orleans where Andrew Jackson led American forces to victory. The war was officially brought to an end with the Treaty of Ghent, where all prisoners were released and pre-war boundaries were restored. All in all, while the Treaty of Ghent didn’t change anything in terms of territory, it reaffirmed American independence and had created a working relationship between the US and Great Britain for years to come. Following the war, the US was relatively peaceful, marking a transition into the so-called Era of Good Feelings. It also really marked the end of the Federalists, who had lost 4 of the past 6 elections. In a last ditch attempt, they hosted the Hartford Convention to air their grievances against the war, but to no avail in revitalizing them. WIth the Election of 1816 coming up, Madison decided to stick to precedent and not run for a 3rd term, paving the way to the presidency of James Monroe.`,
                image: '/images/p3images/baltimore.jpg'
            },
            {
                title: 'Writing Tips',
                body: `Typically party politics come up for this period. LAQs will focus on the comparison between the two parties, such as who votes for who, the policies, and overall trends. Also here, there could be a comparison between the Revolutionary War and War of 1812. There can also be questions about political cartoons like the XYZ affair cartoon.`,
                image: ''
            }
        ]
    },
    period4: {
        sections: [
            {
                title: 'Monroe Presidency',
                body:
                    `The supposed Era of Good Feelings. The Monroe era came after the end of the War of 1812, where the US was now better able to focus on its internal issues. One of the biggest issues was the Compromise of 1820. At the admission of new states, namely Maine and Missouri, a question arose: will these be slave or free states? Some states in the North has begun to be less interested in slavery, while the South preferred to have slaves for their labor and population. These divides would eventually be seen leading to the Civil War throughout the Antebellum Era. In a compromise, organized by Henry Clay, Maine was made a free state while Missouri was a slave state. Beyond this compromise, another big occurrence was the Monroe Doctrine. The Monroe Doctrine was put forth by Secretary of State John Quincy Adams, the son of John Adams, in 1823. The Monroe Doctrine was a warning to European nations to stay out of American affairs, as the British had originally owned the colonies and attempted to weaken it again in 1812, or there would be retaliation. After the end of his 2 terms, per tradition, Monroe did not run for president in 1824.`,
                image: ''
            },
            {
                title: 'Quincy Adams Presidency',
                body:
                    `Former Secretary of State John Quincy Adams won the Election of 1824, partially due to the “corrupt bargain”. The Corrupt Bargain refers to an agreement where Henry Clay helped get votes for John Quincy Adams in order to defeat Andrew Jackson in the election, and in return, he got the position of Secretary of State in Quincy Adams’ cabinet. The corrupt bargain had set in motion the creation of a new political party formed of Jacksonians, the supporters of Andrew Jackson in 1824, called the Democrats. Following his election, Quincy Adams’ one term as president was rather uneventful. As President of the United States, he put forward a system which created highways and canals for easier traversal throughout the nation. In 1828, he lost the election to Andrew Jackson.`,
                image: '/images/p4images/ToT.jpg'
            },
            {
                title: 'Jackson Presidency',
                body:
                    `Andrew Jackson was the first U.S. president to come from the area west of the Appalachians and the first to gain office by a direct appeal to the mass of voters. His political movement has since been known as Jacksonian Democracy. In 1830, Jackson signed the Indian Removal Act, which forcibly relocated most members of the Native American tribes in the South to Indian Territory. The relocation process dispossessed the Indians and resulted in widespread death and disease. Jackson faced the threat of secession by South Carolina over what opponents called the "Tariff of Abominations". The crisis was defused when the tariff was amended, and Jackson threatened the use of military force if South Carolina attempted to secede. Jackson has been widely revered in the United States as an advocate for democracy and the common man. Many of his actions proved divisive, garnering both fervent support and strong opposition from many in the country.`,
                image: '/images/p4images/CB.jpg'
            },
            {
                title: 'Panic of 1837',
                body:
                    `The Panic of 1837 was a financial crisis in the United States that touched off a major depression, which lasted until the mid-1840s. Profits, prices, and wages went down; unemployment went up; and pessimism abounded. The panic had both domestic and foreign origins. Speculative lending practices in the West, a sharp decline in cotton prices, a collapsing land bubble, international specie flows, and restrictive lending policies in Britain were all factors. Conditions in the South were much worse than in the East, and the Cotton Belt was dealt the worst blow. In Virginia, North Carolina, and South Carolina the panic caused an increase in the interest of diversifying crops. Out of 850 banks in the United States, 343 closed entirely, 62 failed partially, and the system of state banks received a shock from which it never fully recovered.The panic unleashed a wave of riots and other forms of domestic unrest. The ultimate result was an increase in the state's police powers, including more professional police forces. In the end, it would seem the main cause of the Panic came from Andrew Jackson’s destruction of the Second Bank of the United States. This, combined with 1 term president Martin Van Buren’s continuation of Jacksonian practices allowed the economic situation to worsen.`,
                image: ''
            },
            {
                title: 'Mexican-American War',
                body: 
                    `The Mexican-American War was fought between the United States and Mexico (April 1846–February 1848) stemming from the United States’ annexation of Texas in 1845 and from a dispute over whether Texas ended at the Nueces River (Mexican claim) or the Rio Grande (U.S. claim). After the start of the Mexican-American War, several members of the house questioned the war’s legality. One of these was Abraham Lincoln. He opposed the declaration of war and introduced the "Spot Resolutions". One of several congressional resolutions opposing the war, it was never acted upon by the full Congress. Lincoln's action temporarily earned him a derisive nickname, "spotty Lincoln," coined by one Illinois newspaper. The war resulted in the United States’ acquisition of more than 500,000 square miles of Mexican territory extending westward from the Rio Grande to the Pacific Ocean. The Treaty of Guadalupe Hidalgo resulted in Mexico ceding nearly all the territory now included in the states of New Mexico, Utah, Nevada, Arizona, California, Texas, and western Colorado for $15 million and U.S. assumption of its citizens’ claims against Mexico.`,
                image: '/images/p4images/MAW.jpg'
            },
            {
                title: 'Seneca Falls Convention',
                body:
                    `The convention was organized by Lucretia Mott and Elizabeth Cady Stanton, two abolitionists who met at the 1840 World Anti-Slavery Convention in London. As women, Mott and Stanton were barred from the convention floor, and the common indignation that this aroused in both of them was the impetus for their founding of the women’s rights movement in the United States. By the time of the National Woman's Rights Convention of 1851, the issue of women's right to vote had become a central tenet of the United States women's rights movement. Abolitionist and former slave Frederick Douglas was invited as well to speak, making the convention a place to move for sweeping social change. These conventions became annual events until the outbreak of the American Civil War in 1861. `,
                image: '/images/p4images/SFC.jpg'
            },
            {
                title: 'Writing Tips',
                body:
                    `In the LAQs for this period, the focus will be on the Jackson presidency and what it did for better or worse. Also, depending on the situation, it is possible to get a prompt on North v South for a Antebellum period essay.`,
                image: ''
            },
            
        ]
    }
}


export default (req, res) => {
    const {
        query: {period},
    } = req

    if (req.method === 'POST') {
        periods[`${period}`].sections = req.body.sections
        res.status(200).json({
            sections: periods[`${period}`].sections
        })
    } else {
        res.statusCode = 200
        res.status(200).json({
            sections: periods[`${period}`].sections
        })
    }
}
